name: canteen_food_ordering_app_v3
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  fluttertoast: ^8.2.2
  uuid: ^4.1.0
  path: ^1.6.4
  progress_dialog_null_safe: ^1.0.7
  curved_navigation_bar: ^1.0.3
  razorpay_flutter: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
